#!/bin/bash

mkdir -p dev/dist
buildpids=""

for f in \
    userapi \
    ; do
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "dev/dist/$f" "./cmd/$f" &
    buildpids+=" $!"
done

for pid in $buildpids; do
    echo "$pid"
    wait "$pid"
done

image="dhij.test/cluster-demo:latest"
docker build -t "$image" -f Dockerfile.dev .
echo "=> dev image built" > /dev/stderr
