#!/bin/bash

set -e

export HOST=${host:-127.0.0.1}
export PORT=${port:-3306}
export USERNAME=${username:-root}
export PASSWORD=${password:-password}
export DATABASE=${database:-users_db}

docker_cmd=(docker run -it --rm --network host --volume "$(pwd)/db:/db" migrate/migrate:v4.17.0)

if [ "${1:-}" == "create" ]; then
    shift
    exec "${docker_cmd[@]}" create -ext sql -dir /db/migrations "$@"
fi

exec "${docker_cmd[@]}" -path=/db/migrations -database "mysql://${USERNAME}:${PASSWORD}@tcp(${HOST}:${PORT})/${DATABASE}" "$@"