#!/bin/bash

set -e
eval "$(dev/variables)"

export HOST=${host:-127.0.0.1}
export PORT=${port:-3306}
export LOGIN=${login:-root}
export PASSWORD=${password:-password}
export DATABASE=${database:-users_db}

docker_cmd=(docker run -it --rm --network host --volume "$(pwd)/db:/db" migrate/migrate:v4.17.0)
echo "host: ${HOST}"

if [ "${1:-}" == "create" ]; then
    shift
    exec "${docker_cmd[@]}" create -ext sql -dir /db/migrations "$@"
fi

exec "${docker_cmd[@]}" -path=/db/migrations -database "mysql://${LOGIN}:${PASSWORD}@tcp(${HOST}:${PORT})/${DATABASE}" "$@"