#!/bin/bash

echo "=> dev building" > /dev/stderr
dev/build &
buildpid=$!

echo "=> dev starting MySQL" > /dev/stderr
docker-compose -f dev/docker-compose.yaml up -d mysql

wait_for "docker-compose -f dev/docker-compose.yaml exec mysql mysql cluster_demo -e 'select 1'"

echo "=> dev starting services" > /dev/stderr
docker-compose -f dev/docker-compose.yaml up -d

echo "=> dev seeding database" > /dev/stderr
dev/migrate up

function wait_for() {
    attempts=0
    while ! eval $@ >/dev/null 2>&1 ; do
        if [[ $attempts -gt 99 ]] ; then
            echo "timed out waiting for $@"
            return 1
        fi
        attempts=$(($attempts+1))
        sleep 3
    done
    return 0
}